version: '3.9'
  
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6397:6397"
    networks:
      - mynetwork

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork